# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newGUI-1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from linearGauge import LinearGauge
from PyQt5.QtCore import QTime, QTimer, QDate, Qt


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1440, 900)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.image = QtWidgets.QLabel(self.centralwidget)
        self.image.setGeometry(QtCore.QRect(0, 0, 1441, 861))
        self.image.setText("")
        self.image.setPixmap(QtGui.QPixmap("pid.png"))
        self.image.setScaledContents(True)
        self.image.setObjectName("image")

        self.machLogo = QtWidgets.QLabel(self.centralwidget)
        self.machLogo.setGeometry(QtCore.QRect(0, 0, 231, 211))
        self.machLogo.setText("")
        self.machLogo.setPixmap(QtGui.QPixmap("RPG LOGO [Recovered]-22.png"))
        self.machLogo.setScaledContents(True)
        self.machLogo.setObjectName("machLogo")

        #set time label
        self.time_label = QtWidgets.QLabel(self.centralwidget)
        self.time_label.setGeometry(QtCore.QRect(260, 30, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Bazooka")
        font.setPointSize(24)
        self.time_label.setFont(font)
        self.time_label.setAlignment(QtCore.Qt.AlignCenter)
        self.time_label.setObjectName("time_label")


        #set date label
        self.date_label = QtWidgets.QLabel(self.centralwidget)
        self.date_label.setGeometry(QtCore.QRect(260, 70, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Bazooka")
        font.setPointSize(18)
        self.date_label.setFont(font)
        self.date_label.setAlignment(QtCore.Qt.AlignCenter)
        self.date_label.setObjectName("date_label")

        #updating the date and time 
        self.timer = QTimer()
        self.timer.timeout.connect(self.update_date_time)
        self.timer.start(1000)  # Update every 1000 milliseconds (1 second)

        self.V34_SB_open = QtWidgets.QPushButton(self.centralwidget)
        self.V34_SB_open.setGeometry(QtCore.QRect(1020, 670, 71, 21))
        self.V34_SB_open.setObjectName("V23_SB_open")
        self.V34_SB_open.setStyleSheet("QPushButton { background-color: #12b81b; color: white; }"
                                       "QPushButton:pressed { background-color: #074d05; }")

        self.V34_SB_close = QtWidgets.QPushButton(self.centralwidget)
        self.V34_SB_close.setGeometry(QtCore.QRect(1020, 700, 71, 21))
        self.V34_SB_close.setObjectName("V34_SB_close")
        self.V34_SB_close.setStyleSheet("QPushButton { background-color: red; color: white; }"
                                       "QPushButton:pressed { background-color: #4d0505; }")

        self.V11_S_NO_open = QtWidgets.QPushButton(self.centralwidget)
        self.V11_S_NO_open.setGeometry(QtCore.QRect(240, 630, 71, 21))
        self.V11_S_NO_open.setObjectName("V11_S_NO_open")
        self.V11_S_NO_open.setStyleSheet("QPushButton { background-color: #12b81b; color: white; }"
                                        "QPushButton:pressed { background-color: #074d05; }")

        self.V11_S_NO_close = QtWidgets.QPushButton(self.centralwidget)
        self.V11_S_NO_close.setGeometry(QtCore.QRect(240, 660, 71, 21))
        self.V11_S_NO_close.setObjectName("V11_S_NO_close")
        self.V11_S_NO_close.setStyleSheet("QPushButton { background-color: red; color: white; }"
                                       "QPushButton:pressed { background-color: #4d0505; }")

        self.V10_SB_open = QtWidgets.QPushButton(self.centralwidget)
        self.V10_SB_open.setGeometry(QtCore.QRect(350, 490, 71, 21))
        self.V10_SB_open.setObjectName("V10_SB_open")
        self.V10_SB_open.setStyleSheet("QPushButton { background-color: #12b81b; color: white; }"
                                       "QPushButton:pressed { background-color: #074d05; }")

        self.V10_SB_close = QtWidgets.QPushButton(self.centralwidget)
        self.V10_SB_close.setGeometry(QtCore.QRect(350, 520, 71, 21))
        self.V10_SB_close.setObjectName("V10_SB_close")
        self.V10_SB_close.setStyleSheet("QPushButton { background-color: red; color: white; }"
                                       "QPushButton:pressed { background-color: #4d0505; }")

        self.V12_S_open = QtWidgets.QPushButton(self.centralwidget)
        self.V12_S_open.setGeometry(QtCore.QRect(410, 280, 71, 21))
        self.V12_S_open.setObjectName("V12_S_open")
        self.V12_S_open.setStyleSheet("QPushButton { background-color: #12b81b; color: white; }"
                                       "QPushButton:pressed { background-color: #074d05; }")

        self.V12_S_close = QtWidgets.QPushButton(self.centralwidget)
        self.V12_S_close.setGeometry(QtCore.QRect(410, 310, 71, 21))
        self.V12_S_close.setObjectName("V12_S_close")
        self.V12_S_close.setStyleSheet("QPushButton { background-color: red; color: white; }"
                                       "QPushButton:pressed { background-color: #4d0505; }")

        self.V32_SB_open = QtWidgets.QPushButton(self.centralwidget)
        self.V32_SB_open.setGeometry(QtCore.QRect(470, 700, 71, 21))
        self.V32_SB_open.setObjectName("V32_SB_open")
        self.V32_SB_open.setStyleSheet("QPushButton { background-color: #12b81b; color: white; }"
                                       "QPushButton:pressed { background-color: #074d05; }")

        self.V32_SB_close = QtWidgets.QPushButton(self.centralwidget)
        self.V32_SB_close.setGeometry(QtCore.QRect(470, 730, 71, 21))
        self.V32_SB_close.setObjectName("V32_SB_close")
        self.V32_SB_close.setStyleSheet("QPushButton { background-color: red; color: white; }"
                                       "QPushButton:pressed { background-color: #4d0505; }")

        self.V33_S_open = QtWidgets.QPushButton(self.centralwidget)
        self.V33_S_open.setGeometry(QtCore.QRect(670, 780, 71, 21))
        self.V33_S_open.setObjectName("V33_S_open")
        self.V33_S_open.setStyleSheet("QPushButton { background-color: #12b81b; color: white; }"
                                       "QPushButton:pressed { background-color: #074d05; }")

        self.V33_S_close = QtWidgets.QPushButton(self.centralwidget)
        self.V33_S_close.setGeometry(QtCore.QRect(670, 810, 71, 21))
        self.V33_S_close.setObjectName("V33_S_close")
        self.V33_S_close.setStyleSheet("QPushButton { background-color: red; color: white; }"
                                       "QPushButton:pressed { background-color: #4d0505; }")

        self.V22_SB_open = QtWidgets.QPushButton(self.centralwidget)
        self.V22_SB_open.setGeometry(QtCore.QRect(550, 180, 71, 21))
        self.V22_SB_open.setObjectName("V22_SB_open")
        self.V22_SB_open.setStyleSheet("QPushButton { background-color: #12b81b; color: white; }"
                                       "QPushButton:pressed { background-color: #074d05; }")

        self.V22_SB_close = QtWidgets.QPushButton(self.centralwidget)
        self.V22_SB_close.setGeometry(QtCore.QRect(550, 210, 71, 21))
        self.V22_SB_close.setObjectName("V22_SB_close")
        self.V22_SB_close.setStyleSheet("QPushButton { background-color: red; color: white; }"
                                       "QPushButton:pressed { background-color: #4d0505; }")

        self.V30_SB_open = QtWidgets.QPushButton(self.centralwidget)
        self.V30_SB_open.setGeometry(QtCore.QRect(1120, 520, 71, 21))
        self.V30_SB_open.setObjectName("V30_SB_open")
        self.V30_SB_open.setStyleSheet("QPushButton { background-color: #12b81b; color: white; }"
                                       "QPushButton:pressed { background-color: #074d05; }")

        self.V30_SB_close = QtWidgets.QPushButton(self.centralwidget)
        self.V30_SB_close.setGeometry(QtCore.QRect(1120, 550, 71, 21))
        self.V30_SB_close.setObjectName("V30_SB_close")
        self.V30_SB_close.setStyleSheet("QPushButton { background-color: red; color: white; }"
                                       "QPushButton:pressed { background-color: #4d0505; }")

        self.V20_SB_open = QtWidgets.QPushButton(self.centralwidget)
        self.V20_SB_open.setGeometry(QtCore.QRect(1070, 200, 71, 21))
        self.V20_SB_open.setObjectName("V20_SB_open")
        self.V20_SB_open.setStyleSheet("QPushButton { background-color: #12b81b; color: white; }"
                                       "QPushButton:pressed { background-color: #074d05; }")

        self.V20_SB_close = QtWidgets.QPushButton(self.centralwidget)
        self.V20_SB_close.setGeometry(QtCore.QRect(1070, 230, 71, 21))
        self.V20_SB_close.setObjectName("V20_SB_close")
        self.V20_SB_close.setStyleSheet("QPushButton { background-color: red; color: white; }"
                                       "QPushButton:pressed { background-color: #4d0505; }")

        self.V35_S_open = QtWidgets.QPushButton(self.centralwidget)
        self.V35_S_open.setGeometry(QtCore.QRect(850, 780, 71, 21))
        self.V35_S_open.setObjectName("V35_S_open")
        self.V35_S_open.setStyleSheet("QPushButton { background-color: #12b81b; color: white; }"
                                       "QPushButton:pressed { background-color: #074d05; }")

        self.V35_S_close = QtWidgets.QPushButton(self.centralwidget)
        self.V35_S_close.setGeometry(QtCore.QRect(850, 810, 71, 21))
        self.V35_S_close.setObjectName("V35_S_close")
        self.V35_S_close.setStyleSheet("QPushButton { background-color: red; color: white; }"
                                       "QPushButton:pressed { background-color: #4d0505; }")
    
        self.P1 = LinearGauge(self.centralwidget)
        self.P1.setGeometry(QtCore.QRect(210, 380, 100, 60))
        self.P1.setObjectName("P1")

        self.P20 = LinearGauge(self.centralwidget)
        self.P20.setGeometry(QtCore.QRect(1330, 400, 100, 60))
        self.P20.setObjectName("P20")

        self.P30 = LinearGauge(self.centralwidget)
        self.P30.setGeometry(QtCore.QRect(1330, 510, 100, 60))
        self.P30.setObjectName("P30")

        self.P3 = LinearGauge(self.centralwidget)
        self.P3.setGeometry(QtCore.QRect(860, 550, 100, 60))
        self.P3.setObjectName("P3")

        self.P2 = LinearGauge(self.centralwidget)
        self.P2.setGeometry(QtCore.QRect(980, 350, 100, 60))
        self.P2.setObjectName("P2")

        self.dialGauge = LinearGauge(self.centralwidget)
        self.dialGauge.setGeometry(QtCore.QRect(1130, 710, 100, 60))
        self.dialGauge.setObjectName("dialGauge")
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1440, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    
    def update_date_time(self): 

        #set the current date and time 
        current_time = QTime.currentTime().toString(Qt.DefaultLocaleLongDate)
        current_date = QDate.currentDate().toString(Qt.DefaultLocaleLongDate)

        #update date and time 
        self.date_label.setText(current_time)
        self.time_label.setText(current_date)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.time_label.setText(_translate("MainWindow", "TextLabel"))
        self.date_label.setText(_translate("MainWindow", "TextLabel"))
        self.V34_SB_open.setText(_translate("MainWindow", "OPEN"))
        self.V34_SB_close.setText(_translate("MainWindow", "CLOSE"))
        self.V11_S_NO_open.setText(_translate("MainWindow", "OPEN"))
        self.V11_S_NO_close.setText(_translate("MainWindow", "CLOSE"))
        self.V10_SB_open.setText(_translate("MainWindow", "OPEN"))
        self.V10_SB_close.setText(_translate("MainWindow", "CLOSE"))
        self.V12_S_open.setText(_translate("MainWindow", "OPEN"))
        self.V12_S_close.setText(_translate("MainWindow", "CLOSE"))
        self.V32_SB_open.setText(_translate("MainWindow", "OPEN"))
        self.V32_SB_close.setText(_translate("MainWindow", "CLOSE"))
        self.V33_S_open.setText(_translate("MainWindow", "OPEN"))
        self.V33_S_close.setText(_translate("MainWindow", "CLOSE"))
        self.V22_SB_open.setText(_translate("MainWindow", "OPEN"))
        self.V22_SB_close.setText(_translate("MainWindow", "CLOSE"))
        self.V30_SB_open.setText(_translate("MainWindow", "OPEN"))
        self.V30_SB_close.setText(_translate("MainWindow", "CLOSE"))
        self.V20_SB_open.setText(_translate("MainWindow", "OPEN"))
        self.V20_SB_close.setText(_translate("MainWindow", "CLOSE"))
        self.V35_S_open.setText(_translate("MainWindow", "OPEN"))
        self.V35_S_close.setText(_translate("MainWindow", "CLOSE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
