# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        MainWindow.setMinimumSize(QtCore.QSize(1080, 720))
        MainWindow.setMaximumSize(QtCore.QSize(1920, 1080))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionpotato1 = QtGui.QAction(parent=MainWindow)
        self.actionpotato1.setObjectName("actionpotato1")
        self.actionpotato2 = QtGui.QAction(parent=MainWindow)
        self.actionpotato2.setObjectName("actionpotato2")
        self.actionbanana1 = QtGui.QAction(parent=MainWindow)
        self.actionbanana1.setObjectName("actionbanana1")
        self.actionbanana2 = QtGui.QAction(parent=MainWindow)
        self.actionbanana2.setObjectName("actionbanana2")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MISSION CONTROL"))
        self.actionpotato1.setText(_translate("MainWindow", "potato1"))
        self.actionpotato2.setText(_translate("MainWindow", "potato2"))
        self.actionbanana1.setText(_translate("MainWindow", "banana1"))
        self.actionbanana2.setText(_translate("MainWindow", "banana2"))
