# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'shiestui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QTime, QTimer, QDate, Qt

from gauge import LinearGauge


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1440, 872)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.image = QtWidgets.QLabel(self.centralwidget)
        self.image.setGeometry(QtCore.QRect(0, 0, 1441, 831))
        self.image.setText("")
        self.image.setPixmap(QtGui.QPixmap("PID2.png"))
        self.image.setScaledContents(True)
        self.image.setObjectName("image")

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(490, 130, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Monserat")
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(490, 160, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")

        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(210, 560, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(210, 590, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(350, 470, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")

        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(410, 260, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")

        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(350, 500, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")

        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(410, 290, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(470, 680, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.pushButton_9.setFont(font)
        self.pushButton_9.setObjectName("pushButton_9")

        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(740, 770, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.pushButton_10.setFont(font)
        self.pushButton_10.setObjectName("pushButton_10")

        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setGeometry(QtCore.QRect(470, 710, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.pushButton_11.setFont(font)
        self.pushButton_11.setObjectName("pushButton_11")

        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_12.setGeometry(QtCore.QRect(740, 800, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.pushButton_12.setFont(font)

        self.pushButton_12.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pushButton_12.setObjectName("pushButton_12")

        self.pushButton_13 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_13.setGeometry(QtCore.QRect(600, 280, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.pushButton_13.setFont(font)
        self.pushButton_13.setObjectName("pushButton_13")

        self.pushButton_14 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_14.setGeometry(QtCore.QRect(600, 250, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.pushButton_14.setFont(font)
        self.pushButton_14.setObjectName("pushButton_14")

        self.pushButton_15 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_15.setGeometry(QtCore.QRect(1130, 480, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.pushButton_15.setFont(font)
        self.pushButton_15.setObjectName("pushButton_15")

        self.pushButton_16 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_16.setGeometry(QtCore.QRect(1130, 510, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.pushButton_16.setFont(font)
        self.pushButton_16.setObjectName("pushButton_16")

        self.pushButton_17 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_17.setGeometry(QtCore.QRect(1070, 210, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.pushButton_17.setFont(font)
        self.pushButton_17.setObjectName("pushButton_17")

        self.pushButton_18 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_18.setGeometry(QtCore.QRect(1070, 180, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.pushButton_18.setFont(font)
        self.pushButton_18.setObjectName("pushButton_18")

        self.pushButton_19 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_19.setGeometry(QtCore.QRect(1010, 630, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.pushButton_19.setFont(font)
        self.pushButton_19.setObjectName("pushButton_19")

        self.pushButton_20 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_20.setGeometry(QtCore.QRect(1010, 660, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.pushButton_20.setFont(font)
        self.pushButton_20.setObjectName("pushButton_20")

        self.pushButton_21 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_21.setGeometry(QtCore.QRect(910, 750, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.pushButton_21.setFont(font)
        self.pushButton_21.setObjectName("pushButton_21")

        self.pushButton_22 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_22.setGeometry(QtCore.QRect(910, 720, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.pushButton_22.setFont(font)
        self.pushButton_22.setObjectName("pushButton_22")

        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(500, 260, 81, 30))
        self.widget.setObjectName("widget")
        self.widget_2 = LinearGauge(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(290, 320, 81, 30))
        self.widget_2.setObjectName("widget_2")

        self.widget_3 = LinearGauge(self.centralwidget)
        self.widget_3.setGeometry(QtCore.QRect(910, 440, 81, 30))
        self.widget_3.setObjectName("widget_3")

        self.widget_4 = LinearGauge(self.centralwidget)
        self.widget_4.setGeometry(QtCore.QRect(1270, 300, 81, 30))
        self.widget_4.setObjectName("widget_4")

        self.widget_5 = LinearGauge(self.centralwidget)
        self.widget_5.setGeometry(QtCore.QRect(1270, 590, 81, 30))
        self.widget_5.setObjectName("widget_5")

        self.widget_6 = LinearGauge(self.centralwidget)
        self.widget_6.setGeometry(QtCore.QRect(950, 490, 81, 30))
        self.widget_6.setObjectName("widget_6")
       
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1440, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.date = QtWidgets.QLabel(self.centralwidget)
        self.date.setGeometry(QtCore.QRect(630, 10, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.date.setFont(font)
        self.date.setAlignment(QtCore.Qt.AlignCenter)
        self.date.setObjectName("label")


        self.time = QtWidgets.QLabel(self.centralwidget)
        self.time.setGeometry(QtCore.QRect(630, 60, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.time.setFont(font)
        self.time.setAlignment(QtCore.Qt.AlignCenter)
        self.time.setObjectName("label_2")
        #updating the date and time 
        self.timer = QTimer()
        self.timer.timeout.connect(self.update_date_time)
        self.timer.start(1000)  # Update every 1000 milliseconds (1 second)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Open"))
        self.pushButton_2.setText(_translate("MainWindow", "Close"))
        self.pushButton_3.setText(_translate("MainWindow", "Open"))
        self.pushButton_4.setText(_translate("MainWindow", "Close"))
        self.pushButton_5.setText(_translate("MainWindow", "Open"))
        self.pushButton_6.setText(_translate("MainWindow", "Open"))
        self.pushButton_7.setText(_translate("MainWindow", "Close"))
        self.pushButton_8.setText(_translate("MainWindow", "Close"))
        self.pushButton_9.setText(_translate("MainWindow", "Open"))
        self.pushButton_10.setText(_translate("MainWindow", "Open"))
        self.pushButton_11.setText(_translate("MainWindow", "Close"))
        self.pushButton_12.setText(_translate("MainWindow", "Close"))
        self.pushButton_13.setText(_translate("MainWindow", "Close"))
        self.pushButton_14.setText(_translate("MainWindow", "Open"))
        self.pushButton_15.setText(_translate("MainWindow", "Open"))
        self.pushButton_16.setText(_translate("MainWindow", "Close"))
        self.pushButton_17.setText(_translate("MainWindow", "Close"))
        self.pushButton_18.setText(_translate("MainWindow", "Open"))
        self.pushButton_19.setText(_translate("MainWindow", "Open"))
        self.pushButton_20.setText(_translate("MainWindow", "Close"))
        self.pushButton_21.setText(_translate("MainWindow", "Close"))
        self.pushButton_22.setText(_translate("MainWindow", "Open"))

    #method for updating date and time 
    def update_date_time(self): 

        #set the current date and time 
        current_time = QTime.currentTime().toString(Qt.DefaultLocaleLongDate)
        current_date = QDate.currentDate().toString(Qt.DefaultLocaleLongDate)

        #update date and time 
        self.date.setText(current_time)
        self.time.setText(current_date)



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
